In [23]:
import pandas as pd

In [24]:
def clean_data_for_clustering(df):
    """
    Prepares dataset for Unsupervised Clustering.
    Extracts product identity by combining name and categories.
    """
    # Select relevant columns
    df_clean = df[["name", "categories"]].copy()

    # Drop entries without a product name 
    df_clean = df_clean.dropna(subset=["name"])
    
    # Fill missing categories with an empty string so the combination doesn't fail
    df_clean["categories"] = df_clean["categories"].fillna("")

    # Combine name and categories into a single string 
    df_clean["product_info"] = (
        df_clean["name"].astype(str) + " " + df_clean["categories"].astype(str)
    ).str.lower()

    # Remove duplicates
    df_unique = df_clean.drop_duplicates(subset=["name"]).reset_index(drop=True)

    return df_unique["product_info"]

In [25]:
# Load and clean the data 
data = pd.read_csv("../data/1429_1.csv")
product_list = clean_data_for_clustering(data).to_list()
data.head()

/var/folders/gn/wg9xjv455tj2c2jns2j4b8yw0000gn/T/ipykernel_99377/1602615083.py:2: DtypeWarning: Columns (0: name, 1: reviews.didPurchase) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../data/1429_1.csv")

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.doRecommend,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username
0,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,This product so far has not disappointed. My c...,Kindle,NaN,NaN,Adapter
1,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,great for beginner or experienced person. Boug...,very fast,NaN,NaN,truman
2,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,NaN,NaN,DaveZ
3,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5620406/review...,I've had my Fire HD 8 two weeks now and I love...,Good!!!,NaN,NaN,Shacks
4,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-12T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,NaN,NaN,explore42

In [26]:
from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans

# Embed cleaned strings 
embedder = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = embedder.encode(product_list)

# Perform K-Means Clustering
num_clusters = 5
kmeans = KMeans(n_clusters=num_clusters, random_state=42, n_init=10)
cluster_labels = kmeans.fit_predict(embeddings)

# Store results in dataframe for inspection
results = pd.DataFrame({
    "product_info": product_list,
    "cluster": cluster_labels
})

# Check the clusters 
for i in range(num_clusters):
    print(f"\n--- Cluster {i} Sample Items ---")
    print(results[results["cluster"] == i]["product_info"].head(3).values)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 8903.82it/s]

--- Cluster 0 Sample Items ---
<ArrowStringArray>
[                                                                                                                                                                                                                                                                                                                  'kindle oasis e-reader with leather charging cover - merlot, 6 high-resolution display (300 ppi), wi-fi - includes special offers,, ebook readers,kindle e-readers,computers & tablets,e-readers & accessories,e-readers',
                                                                                                                                                                                                                                                              'kindle oasis e-reader with leather charging cover - black, 6 high-resolution display (300 ppi), wi-fi - includes special offers,, fire tablets,tablets,computers & tablets,all tablets,electronics, tech toys, movies, music,electronics,ipad & tablets,android tablets,frys',
 'kindle voyage e-reader, 6 high-resolution display (300 ppi) with adaptive built-in light, pagepress sensors, wi-fi - includes special offers, walmart for business,office electronics,tablets,office,electronics,ipad & tablets,windows tablets,all windows tablets,computers & tablets,e-readers & accessories,e-readers,ebook readers,kindle e-readers,computers/tablets & networking,tablets & ebook readers,electronics features,books & magazines,book accessories,ereaders,tvs & electronics,computers & laptops,tablets & ereaders']
Length: 3, dtype: str

--- Cluster 1 Sample Items ---
<ArrowStringArray>
[                                                'amazon 5w usb official oem charger and power adapter for fire tablets and kindle ereaders,,,\r\namazon 5w usb official oem charger and power adapter for fire tablets and kindle ereaders,,, tablets,fire tablets,computers & tablets,all tablets',
                                           'amazon - kindle voyage - 4gb - wi-fi + 3g - black,,,\r\namazon - kindle voyage - 4gb - wi-fi + 3g - black,,, fire tablets,tablets,computers & tablets,all tablets,electronics, tech toys, movies, music,electronics,ipad & tablets,android tablets,frys',
 'amazon standing protective case for fire hd 6 (4th generation) - black,,,\r\namazon standing protective case for fire hd 6 (4th generation) - black,,, fire tablets,tablets,computers & tablets,all tablets,electronics, tech toys, movies, music,electronics,ipad & tablets,android tablets,frys']
Length: 3, dtype: str

--- Cluster 2 Sample Items ---
<ArrowStringArray>
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'echo (white),,,\r\necho (white),,, fire tablets,tablets,computers & tablets,all tablets,computers/tablets & networking,tablets & ebook readers',
 'echo (white),,,\r\nfire tablet, 7 display, wi-fi, 8 gb - includes special offers, tangerine" stereos,remote controls,amazon echo,audio docks & mini speakers,amazon echo accessories,kitchen & dining features,speaker systems,electronics,tvs entertainment,clearance,smart hubs & wireless routers,featured brands,wireless speakers,smart home & connected living,home security,kindle store,home automation,home, garage & office,home,voice-enabled smart assistants,virtual assistant speakers,portable audio & headphones,electronics features,amazon device accessories,ipod, audio player accessories,home & furniture clearance,consumer electronics,smart home,surveillance,home improvement,smart home & home automation devices,smart hubs,home safety & security,voice assistants,alarms & sensors,amazon devices,audio,holiday shop',
                                                           'echo (black),,,\r\necho (black),,, stereos,remote controls,amazon echo,audio docks & mini speakers,amazon echo accessories,kitchen & dining features,speaker systems,electronics,tvs entertainment,clearance,smart hubs & wireless routers,featured brands,wireless speakers,smart home & connected living,home security,kindle store,home automation,home, garage & office,home,voice-enabled smart assistants,virtual assistant speakers,portable audio & headphones,electronics features,amazon device accessories,ipod, audio player accessories,home & furniture clearance,consumer electronics,smart home,surveillance,home improvement,smart home & home automation devices,smart hubs,home safety & security,voice assistants,alarms & sensors,amazon devices,audio,holiday shop']
Length: 3, dtype: str

--- Cluster 3 Sample Items ---
<ArrowStringArray>
['amazon kindle lighted leather cover,,,\r\namazon kindle lighted leather cover,,, electronics,ebook readers & accessories,covers,kindle store,amazon device accessories,kindle e-reader accessories,kindle (5th generation) accessories,kindle (5th generation) covers',
                     'amazon kindle lighted leather cover,,,\r\nkindle keyboard,,, electronics,ebook readers & accessories,covers,kindle store,amazon device accessories,kindle e-reader accessories,kindle (5th generation) accessories,kindle (5th generation) covers',
                                         'kindle keyboard,,,\r\nkindle keyboard,,, electronics,ebook readers & accessories,covers,kindle store,amazon device accessories,kindle e-reader accessories,kindle (5th generation) accessories,kindle (5th generation) covers']
Length: 3, dtype: str

--- Cluster 4 Sample Items ---
<ArrowStringArray>
[                                'all-new fire hd 8 tablet, 8 hd display, wi-fi, 16 gb - includes special offers, magenta electronics,ipad & tablets,all tablets,fire tablets,tablets,computers & tablets',
                                                                         'all-new fire hd 8 tablet, 8 hd display, wi-fi, 32 gb - includes special offers, magenta kindle store,amazon devices,electronics',
 'fire hd 8 tablet with alexa, 8 hd display, 32 gb, tangerine - with special offers, tablets,fire tablets,electronics,computers,computer components,hard drives & storage,computers & tablets,all tablets']
Length: 3, dtype: str

In [27]:
# Dictionary of unique products
name_to_cluster = dict(zip(results["product_info"], results["cluster"]))

# Recreate product info logic on entire dataset 
data["temp_id_key"] = (
    data["name"].astype(str) + " " + data["categories"].astype(str)
).str.lower()

# Map using the new key
data["cluster_id"] = data["temp_id_key"].map(name_to_cluster)

# Clean up: Drop the temporary key and rows without a cluster
data = data.drop(columns=["temp_id_key"])

print(data[["name", "cluster_id"]].head())

                                                name  cluster_id
0  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...         4.0
1  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...         4.0
2  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...         4.0
3  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...         4.0
4  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...         4.0

In [28]:
import re

def distill_cluster_v2(results_df, cluster_id):
    unique_names = results_df[results_df["cluster"] == cluster_id]["product_info"].unique()
    
    clean_set = set() # Set to avoid identical 'first 10 words'
    for name in unique_names:
        clean_name = re.sub(r"[^a-zA-Z0-9\s]", " ", name)
        clean_name = " ".join(clean_name.split()[:10]).lower()
        clean_set.add(clean_name)
    
    # Return up to 10 unique variations
    return "\n- ".join(list(clean_set)[:10])

print(distill_cluster_v2(results, 3.0))

amazon kindle fire hd 3rd generation 8gb amazon kindle fire
- kindle keyboard kindle keyboard electronics ebook readers accessories covers kindle
- amazon kindle lighted leather cover kindle keyboard electronics ebook readers
- all new kindle e reader black 6 glare free touchscreen
- amazon kindle lighted leather cover amazon kindle lighted leather cover

In [29]:
import os
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


def get_professional_label(distilled_text):
    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini", 
            messages=[
                {"role": "system", "content": "You are a retail data expert. Your task is to provide a single, professional 2-3 word category name that summarizes a list of products. Avoid being too specific (e.g., use 'Tableware' instead of 'Plates'). Return ONLY the category name."},
                {"role": "user", "content": f"Product List:\n{distilled_text}"}
            ],
            temperature=0 
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        return "Uncategorized"

print(get_professional_label(distill_cluster_v2(results, 1.0)))

Smart Devices

In [30]:
# Create mapping for clustering labels 
c_labels_map = {}
existing_labels = set()
unique_clusters = [c for c in data["cluster_id"].unique() if pd.notna(c)]

for cluster in unique_clusters:
    cluster_key = int(cluster)
    label = get_professional_label(distill_cluster_v2(results, cluster_key))
    if label in existing_labels:
        label = f"{label} (Group {cluster_key})"
    
    c_labels_map[cluster_key] = label
    existing_labels.add(label)

In [31]:
data["cluster"] = data["cluster_id"].map(c_labels_map).fillna("Miscellaneous")
data.head()

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,cluster_id,cluster
0,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,This product so far has not disappointed. My c...,Kindle,NaN,NaN,Adapter,4.0,Tablets
1,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,great for beginner or experienced person. Boug...,very fast,NaN,NaN,truman,4.0,Tablets
2,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,NaN,NaN,DaveZ,4.0,Tablets
3,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,0.0,4.0,http://reviews.bestbuy.com/3545/5620406/review...,I've had my Fire HD 8 two weeks now and I love...,Good!!!,NaN,NaN,Shacks,4.0,Tablets
4,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-12T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,NaN,NaN,explore42,4.0,Tablets